spring.application.name=tn-entrenamientos
server.port=8083

# Base de datos MySQL para entrenamientos
spring.datasource.url=jdbc:mysql://localhost:3306/tn_entrenamientos_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Perfil dev para permitir todo (incluido en DevSecurityConfig)
# spring.profiles.active=dev

# Configuración de clientes HTTP hacia otros microservicios
clients.usuarios.base-url=http://localhost:8081
clients.biblioteca.base-url=http://localhost:8082
